### PR TITLE
Added implicit directory creation and directory check

### PR DESCRIPTION
**Pull request by ghost**
Somehow related to https://github.com/thephpleague/flysystem-ziparchive/issues/7

The behavior also happens when trying to create a zipfile in a folder which does not exist. This opposes the "This means directories are second class citizens. Because of this, directories will be automatically created on file systems that require them when writing files. " paradigma.

More important: FlySystem _does not tell me_ something went wrong. You just can't find the file anywhere. It's completly different in the behaviour then lets say the LocalAdapter:

```
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local as LocalAdapter;

$fs = new Filesystem(new LocalAdapter('path/does/not/exist/'));

$fs->write('helloworld.txt','hello world');
```

What happens here: I will find a folder(structure) path/does/not/exist/ in my current directory (the write() is not necessary for this). After the write() the file helloworld.txt will be there as well. If the folder is invalid and/or can not be created an Exception is thrown.

Now, when I try this with ZipArchive adapter:

```
use League\Flysystem\Filesystem;
use League\Flysystem\ZipArchive\ZipArchiveAdapter;

$fs = new Filesystem(new ZipArchiveAdapter('path/does/not/exist/helloworld.zip'));

$resultWrite = $fs->write('helloworld.txt','hello world');

var_dump($resultWrite);

$resultClose = $fs->getAdapter()->getArchive()->close();

var_dump($resultClose);
```

var_dump($resultWrite) -> will return true
var_dump($resultClose) -> will return false. 

This (and a PHP warning) is _all_ the information I get that something went wrong and my file can not be found anywhere. When I don't close the archive manually and rely on the destructor I will just get the warning, nothing else.

To be fair, this also happens when working with native ZipArchive - it does all the actual file handling when calling the close()-method - it then returns false.

But the point in using FlySystem and it's adapters is because of the abstraction and interoperability. So in my opinion the adapter should act like the other ones or _at least_ tell me when something went wrong. 

Handling the directory checks outside the adapter like recommended in #7 is clearly inconsistent compared to the LocalAdapter. 

To change this, I ported some of the functionality of the LocalAdapter to the ZipArchiveAdapter. I had to c&p because of the different repositories - otherwise some unification would be handy. I also didn't really implement the permission handling, this could be added later. (To avoid the "starting at a, ending at z" effect, when just trying to fix _one_ thing ;-)).

### CODE REVIEW

**Comment by ghost** [comment]
@frankdejonge what's your opinion on this?

**Comment by frankdejonge** [comment]
@bassblau I'm not sure I like this. It feels like the storage would now be overreaching. Flysystem's "principles" do indeed include creating directories implicitly, but in this case it'd cross isolation boundary, which makes it different.

**Comment by ghost** [comment]
@frankdejonge Hm, I understand your concerns, but to me the whole ZipArchive adapter feels "special" and (in some way) out of line compared to the other adapters*. Going the "do your checks outside of Flysystem/Filesystem" way is completely different to the other adapters* and it's not much benefit left of the adapter over lets say an native ZipArchive implementation.

(* Adapter I used so far)

**Comment by FrankGiesecke** [comment]
As I see, the `\League\Flysystem\Adapter\Local` does the same handling as the fix made by @bassblau.

**Comment by unguul** [comment]
I know this is an old PR but `ZipArchiveAdapter` was just failing with
```
PHP Warning:  ZipArchive::close(): Failure to create temporary file: No such file or directory 
```
This was quite confusing as I was expecting the adapter to simply create the required directories.

Perhaps you could reconsider?

**Comment by ghost** [comment]
@unguul: It took the maintainer more then half a year and a explicit mention to respond and no more response since then. Also no new commits at all in this repo. I think it's safe to say you either use this adapter "as is", fork and adjust it yourself (or use mine) or just avoid it.

**Comment by frankdejonge** [comment]
@bassblau it takes the maintainer a significant chunk of his free time that he's spent maintaining all the different adapter. Even in this year where he doesn't even use PHP in his day job. So, yeah, sometimes some things fall through and don't get picked up. You can always just extend the adapter's. Nothing is blocking you. But remarks like this don't really motivate me to fix your issue.

**Comment by ghost** [comment]
@frankdejonge I know you do **a lot** for the php eco system. Don't get me wrong here.

But please try to understand my perspective as well: 

1. I stumble over an issue in october 2016. Analyze it, try to understand what's happening. Try to improve/fix it in the best way I could back then. In short: put my own free time into this. When you check my GitHub profile you will see I'm by far no power user or widely known contributor like you are. But I did not shy away, and opened my very first pull request.
2. Nothing happens, I don't know how to react to this and just use my fork. 
3. In march 2017 I asked you about your opinion on this still open PR, get an "Well I don't really like it" as an answer. I try to explain my point of view. No response.
4. In june 2017 another user seconds my point. No response.
5. I stopped caring and didn't see a way to get my issue resolved. I just used my fork and assumed this repository as (pretty much) dead.
6. Almost 2 years later someone comments on this still open PR.
7. I am making a resigned comment stating the options I saw at this point, not even expecting a  response based on my experience.
8. You're reacting insulted.

Anyway. I'm still open for discussions on this.

**Comment by twistor** [comment]
Thanks for your contribution. We decline accepting it.

There's a big difference between creating directories automatically inside a filesystem and outside one.

That the local adapter will create the root directory upon creation is a mistake.

We don't wish to continue that mistake to other adapters.

**Pull request closed without merging**
